### ISSUE TITLE
Open linked attachments

### ISSUE THREAD

**Issue by smathot** [smathot/qnotero#15]

**Comment by firstuanl** [comment]
can not open link attachment
also copy to tmp,but
`libzotero.search(): retrieving results for '波浪' from cache
qnoteroResults.mousePressEvent(): prepare to copy b'/home/firstuanl/iBooks/\xe6\xb3\xa2\xe6\xb5\xaa/\xe8\x89\xbe\xe7\x95\xa5\xe7\x89\xb9\xe5\x90\x8d\xe8\x91\x97\xe9\x9b\x86.pdf'
qnoteroResults.mousePressEvent(): prepare to copy (tmp) /tmp/（美）普莱切特 & 陈鑫 (2003).pdf
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/libqnotero/qnoteroResults.py", line 90, in mousePressEvent
    mimeData.setData("text/plain", tmpFile)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-11: ordinal not in range(256)
gvfs-open: /home/firstuanl/iBooks/æ³¢æµª/è¾ç¥ç¹å
`
