### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by melsophos** [smathot/qnotero#20]
It would be very useful to have few shortcuts for interacting with qnotero (especially the first one):

- some user-defined shortcut for opening the main window;
- one for going into the search bar if the "focus" has been lost (for example by clicking on some items in the result), e.g. "ctrl + f";
- a last one to quite the program, such as "ctrl + q".

**Comment by smathot** [comment]
To start the main window, you can use your operating system's keyboard shortcuts to launch `qnotero`. This will activate qnotero if it is already running. However, a focus shortcut (`ctrl+f`) seems like a useful addition.

**Comment by melsophos** [comment]
Thanks for the advise, I will do that!
